### PR TITLE
Fix opensvc

### PR DESCRIPTION
**Pull request by arnaudveron**

### CODE REVIEW

**Comment by frequent** [comment]
Hey @arnaudveron : will have a look, thank for the pull request

**Comment by frequent** [comment]
I have to double check if the "Application" category fits, then I will merge.

**Comment by arnaudveron** [comment]
Hi. Any update on the "Application" topic ? Thanks.

**Comment by frequent** [comment]
@arnaudveron 

I took the modifications from your merge request and updated the file manually, since I'm short on time to fix the merge conflicts. Here is the commit I just added:
https://github.com/Fonds-de-Dotation-du-Libre/european-cloud-industry/commit/2f7384fd055151ef66266dd52177c514ea588fcc

Please note, that I changed the category back to "Service lifecycle automation". Our definition for "Application" is
_Any application software (ERP, CRM, HR, etc.) which can be provided as SaaS and which is not a workspace or a cybersecutity application for which dedicated categories exist (eg. Erp5)_

The whole dataset uses this definition of "Application", so we cannot deviate from it. I will put all definition on the guideline document.

Could you double check if the file is ok now and if not open another PR => https://github.com/Fonds-de-Dotation-du-Libre/european-cloud-industry/blob/master/opensvc.json 

Thanks and I'm closing this PR.

**Pull request closed without merging**
